import fs from 'fs';
import path from 'path';
import Parser from 'rss-parser';
import { scoreStory } from '../lib/scoring';
import crypto from 'crypto';

const parser = new Parser({
  timeout: 10000,
});

async function main() {
  const sourcesPath = path.join(process.cwd(), 'data', 'sources.json');
  const newsPath = path.join(process.cwd(), 'data', 'news.json');

  const sources = JSON.parse(fs.readFileSync(sourcesPath, 'utf8'));
  let newsData = {
    fetchedAt: new Date().toISOString(),
    note: '',
    sources: { ok: 0, failed: [] as string[] },
    stories: [] as any[],
  };

  if (fs.existsSync(newsPath)) {
    const existing = JSON.parse(fs.readFileSync(newsPath, 'utf8'));
    // Clear sample note if exists
    newsData.stories = existing.stories.filter((s: any) => s.id !== 'sample-1');
  }

  const enabledSources = sources.filter((s: any) => s.enabled);
  const existingUrls = new Set(newsData.stories.map(s => s.url));
  const newStories: any[] = [];
  
  let okCount = 0;
  const failed: string[] = [];

  for (const source of enabledSources) {
    try {
      console.log(`Fetching ${source.name}...`);
      const feed = await parser.parseURL(source.feedUrl);
      okCount++;

      for (const item of feed.items) {
        if (!item.link) continue;
        if (existingUrls.has(item.link)) continue; // Already have it

        const content = item.contentSnippet || item.content || '';
        const score = scoreStory(item.title || '', content);
        
        let importance = 'worth-knowing';
        if (score >= 4) importance = 'must-see';
        else if (score === 1) importance = 'background';

        newStories.push({
          id: crypto.createHash('md5').update(item.link).digest('hex'),
          title: item.title || 'Untitled',
          url: item.link,
          sourceId: source.id,
          sourceName: source.name,
          publishedAt: item.isoDate || item.pubDate || new Date().toISOString(),
          excerpt: content.substring(0, 160) + (content.length > 160 ? '...' : ''),
          category: source.category || 'general',
          importance,
          career: false,
          readMinutes: Math.ceil(content.length / 1000) || 5,
          score,
          archived: false,
          read: false
        });
        existingUrls.add(item.link);
      }
    } catch (err: any) {
      console.error(`Failed to fetch ${source.name}: ${err.message}`);
      failed.push(source.id);
    }
  }

  // Sort new stories by date descending before adding
  newStories.sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime());

  // "never removes or reorders existing ones, and preserves every archived and read flag."
  newsData.stories = [...newStories, ...newsData.stories];
  newsData.sources.ok = okCount;
  newsData.sources.failed = failed;
  newsData.fetchedAt = new Date().toISOString();
  newsData.note = 'Generated by scripts/fetchNews.ts';

  fs.writeFileSync(newsPath, JSON.stringify(newsData, null, 2), 'utf8');
  console.log(`Fetch complete. Added ${newStories.length} new stories.`);
}

main().catch(console.error);
